/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserAccount;



import java.awt.Color;
import javax.swing.ImageIcon;
import EgyEast.Home.*;
import static EgyEast.Home.*;
import FavPage.FavFrame;
import static FavPage.RowsCardsFav.filmCardsFav;
import com.mycompany.egyeastlogin.CurrentUser;
import static com.mycompany.egyeastlogin.EgyEastLogin.favFrame;
import static com.mycompany.egyeastlogin.EgyEastLogin.home;
import static com.mycompany.egyeastlogin.EgyEastLogin.login;
import static com.mycompany.egyeastlogin.EgyEastLogin.updateData;
import static com.mycompany.egyeastlogin.EgyEastLogin.user_account;
import static com.mycompany.egyeastlogin.EgyEastLogin.user_data;
import com.mycompany.egyeastlogin.SignUp;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class User_account extends javax.swing.JFrame {
    /**
     * Creates new form User_account
     */
    
    
    
    public User_account() {
        initComponents();
        ImageIcon img = new ImageIcon("C:\\EgyEast_Image\\icons/EgyEast.png");
          this.setIconImage(img.getImage());
        try {
            big_name.setText(CurrentUser.user_data.getString("Name"));
            if (CurrentUser.user_data.getInt("Plan_id") == 1){
                 big_plan.setText("Gold Plan");
            }
            else if (CurrentUser.user_data.getInt("Plan_id") == 2){
                 big_plan.setText("Platinum Plan");
            }
            else if (CurrentUser.user_data.getInt("Plan_id") == 3){
                 big_plan.setText("Diamond Plan");
            }
            name_tf.setText(CurrentUser.user_data.getString("Name"));
            gender_Cb.setSelectedItem(CurrentUser.user_data.getString("Gender"));
            country_Cb.setSelectedItem(CurrentUser.user_data.getString("Country"));
            age_tf.setText(CurrentUser.user_data.getString("Age"));
            phone_tf.setText(CurrentUser.user_data.getString("phone"));
            email_tf.setText(CurrentUser.user_data.getString("Email"));
            //plan_Group.setSelected((ButtonModel) gold_btn, rootPaneCheckingEnabled);
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(User_account.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plan_Group = new javax.swing.ButtonGroup();
        lbar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        homebtn = new EgyEast.com.roundedpanal.RoundedPanel();
        homebtnl = new javax.swing.JLabel();
        homeImage = new ImagePrint.ImagePanel();
        logoutbtn = new EgyEast.com.roundedpanal.RoundedPanel();
        logoutbtnl = new javax.swing.JLabel();
        logout = new ImagePrint.ImagePanel();
        favouritesbtn = new EgyEast.com.roundedpanal.RoundedPanel();
        favourtiebtnl = new javax.swing.JLabel();
        favourites = new ImagePrint.ImagePanel();
        profilebtn = new EgyEast.com.roundedpanal.RoundedPanel();
        profilebtnl = new javax.swing.JLabel();
        profile = new ImagePrint.ImagePanel();
        main_panel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        gender_Cb = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        country_Cb = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        email_tf = new javax.swing.JTextField();
        new_password_tf = new javax.swing.JPasswordField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        phone_tf = new javax.swing.JTextField();
        name_tf = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        age_tf = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        old_password_tf = new javax.swing.JPasswordField();
        jSeparator9 = new javax.swing.JSeparator();
        new_password2_tf = new javax.swing.JPasswordField();
        jLabel30 = new javax.swing.JLabel();
        myButton2 = new newpackage.myButton();
        roundedPanel1 = new newpackage.RoundedPanel();
        myButton1 = new newpackage.myButton();
        platinum_btn = new javax.swing.JRadioButton();
        gold_btn = new javax.swing.JRadioButton();
        Diamond_btn = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        big_name = new javax.swing.JLabel();
        big_plan = new javax.swing.JLabel();
        imagePanel2 = new ImagePanel.ImagePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EgyEast");
        setBackground(new java.awt.Color(19, 20, 28));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setFocusTraversalPolicyProvider(true);
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);

        lbar.setBackground(new java.awt.Color(30, 32, 44));
        lbar.setPreferredSize(new java.awt.Dimension(210, 800));
        lbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(30, 32, 44));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Rubik", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(11, 149, 255));
        jLabel3.setText("EgyEast");
        jPanel4.add(jLabel3, new java.awt.GridBagConstraints());

        lbar.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 80));

        homebtn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {

                homebtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            }

            @Override
            public void mouseExited(MouseEvent e) {

                homebtn.setCursor(Cursor.getDefaultCursor());
            }
        });
        homebtn.setBackground(new java.awt.Color(30, 32, 44));
        homebtn.setForeground(new java.awt.Color(30, 32, 44));
        homebtn.setPreferredSize(new java.awt.Dimension(204, 49));
        homebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homebtnMousePressed(evt);
            }
        });
        homebtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homebtnl.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        homebtnl.setForeground(new java.awt.Color(242, 242, 242));
        homebtnl.setText("Home");
        homebtnl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homebtnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homebtnlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homebtnlMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homebtnlMousePressed(evt);
            }
        });
        homebtn.add(homebtnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 120, 50));

        homeImage.setMinimumSize(new java.awt.Dimension(25, 25));
        homeImage.setPreferredSize(new java.awt.Dimension(24, 24));
        homeImage.setImage("C:\\EgyEast_Image\\icons\\Home.png");
        homeImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeImageMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeImageMousePressed(evt);
            }
        });

        javax.swing.GroupLayout homeImageLayout = new javax.swing.GroupLayout(homeImage);
        homeImage.setLayout(homeImageLayout);
        homeImageLayout.setHorizontalGroup(
            homeImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        homeImageLayout.setVerticalGroup(
            homeImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        homebtn.add(homeImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lbar.add(homebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        logoutbtn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {

                logoutbtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            }

            @Override
            public void mouseExited(MouseEvent e) {

                logoutbtn.setCursor(Cursor.getDefaultCursor());
            }
        });
        logoutbtn.setBackground(new java.awt.Color(30, 32, 44));
        logoutbtn.setForeground(new java.awt.Color(30, 32, 44));
        logoutbtn.setPreferredSize(new java.awt.Dimension(204, 49));
        logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutbtnMousePressed(evt);
            }
        });
        logoutbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutbtnl.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        logoutbtnl.setForeground(new java.awt.Color(242, 242, 242));
        logoutbtnl.setText("Logout");
        logoutbtnl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutbtnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutbtnlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutbtnlMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutbtnlMousePressed(evt);
            }
        });
        logoutbtn.add(logoutbtnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 120, 50));

        logout.setMinimumSize(new java.awt.Dimension(25, 25));
        logout.setImage("C:\\EgyEast_Image\\icons\\Logout.png");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
        });

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        logoutbtn.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lbar.add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, -1, -1));

        favouritesbtn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {

                favouritesbtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            }

            @Override
            public void mouseExited(MouseEvent e) {

                favouritesbtn.setCursor(Cursor.getDefaultCursor());
            }
        });
        favouritesbtn.setBackground(new java.awt.Color(30, 32, 44));
        favouritesbtn.setForeground(new java.awt.Color(30, 32, 44));
        favouritesbtn.setPreferredSize(new java.awt.Dimension(204, 49));
        favouritesbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                favouritesbtnMousePressed(evt);
            }
        });
        favouritesbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        favourtiebtnl.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        favourtiebtnl.setForeground(new java.awt.Color(242, 242, 242));
        favourtiebtnl.setText("Favourites");
        favourtiebtnl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        favourtiebtnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                favourtiebtnlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                favourtiebtnlMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                favourtiebtnlMousePressed(evt);
            }
        });
        favouritesbtn.add(favourtiebtnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 120, 50));

        favourites.setMinimumSize(new java.awt.Dimension(25, 25));
        favourites.setPreferredSize(new java.awt.Dimension(24, 24));
        favourites.setImage("C:\\EgyEast_Image\\icons\\Heart.png");
        favourites.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                favouritesMousePressed(evt);
            }
        });

        javax.swing.GroupLayout favouritesLayout = new javax.swing.GroupLayout(favourites);
        favourites.setLayout(favouritesLayout);
        favouritesLayout.setHorizontalGroup(
            favouritesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        favouritesLayout.setVerticalGroup(
            favouritesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        favouritesbtn.add(favourites, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lbar.add(favouritesbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        profilebtn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {

                profilebtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            }

            @Override
            public void mouseExited(MouseEvent e) {

                profilebtn.setCursor(Cursor.getDefaultCursor());
            }
        });
        profilebtn.setBackground(new java.awt.Color(19, 20, 28));
        profilebtn.setForeground(new java.awt.Color(11, 149, 255));
        profilebtn.setPreferredSize(new java.awt.Dimension(204, 49));
        profilebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                profilebtnMousePressed(evt);
            }
        });
        profilebtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profilebtnl.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        profilebtnl.setForeground(new java.awt.Color(242, 242, 242));
        profilebtnl.setText("Profile");
        profilebtnl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profilebtnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profilebtnlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profilebtnlMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                profilebtnlMousePressed(evt);
            }
        });
        profilebtn.add(profilebtnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 120, 50));

        profile.setMinimumSize(new java.awt.Dimension(25, 25));
        profile.setPreferredSize(new java.awt.Dimension(24, 24));
        profile.setImage("C:\\EgyEast_Image\\icons\\Profile-clicked.png");
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                profileMousePressed(evt);
            }
        });

        javax.swing.GroupLayout profileLayout = new javax.swing.GroupLayout(profile);
        profile.setLayout(profileLayout);
        profileLayout.setHorizontalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        profileLayout.setVerticalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        profilebtn.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lbar.add(profilebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        main_panel.setBackground(new java.awt.Color(19, 20, 28));
        main_panel.setForeground(new java.awt.Color(19, 20, 28));
        main_panel.setPreferredSize(new java.awt.Dimension(800, 800));
        main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(0, 153, 255));
        jLabel12.setFont(new java.awt.Font("Rubik", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 255));
        jLabel12.setText("Contact Details");
        main_panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 331, 160, 34));

        jLabel13.setBackground(new java.awt.Color(0, 153, 255));
        jLabel13.setFont(new java.awt.Font("Rubik", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 255));
        jLabel13.setText("Personal Details");
        main_panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 12, 160, 34));

        jLabel14.setFont(new java.awt.Font("Rubik", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(136, 140, 173));
        jLabel14.setText("Name");
        main_panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 56, -1));

        jLabel15.setFont(new java.awt.Font("Rubik", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(136, 140, 173));
        jLabel15.setText("Age");
        main_panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 258, -1, -1));

        jLabel16.setFont(new java.awt.Font("Rubik", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(136, 140, 173));
        jLabel16.setText("Gender");
        main_panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 127, 70, -1));

        gender_Cb.setBackground(new java.awt.Color(19, 20, 28));
        gender_Cb.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        gender_Cb.setForeground(new java.awt.Color(204, 204, 204));
        gender_Cb.setMaximumRowCount(2);
        gender_Cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        gender_Cb.setToolTipText("");
        gender_Cb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 32, 44), 1, true));
        gender_Cb.setFocusable(false);
        gender_Cb.setLightWeightPopupEnabled(false);
        gender_Cb.setVerifyInputWhenFocusTarget(false);
        main_panel.add(gender_Cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 151, 242, 31));

        jLabel17.setFont(new java.awt.Font("Rubik", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(136, 140, 173));
        jLabel17.setText("Country");
        main_panel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 188, -1, -1));

        country_Cb.setBackground(new java.awt.Color(19, 20, 28));
        country_Cb.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        country_Cb.setForeground(new java.awt.Color(204, 204, 204));
        country_Cb.setMaximumRowCount(22);
        country_Cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Algeria", "Bahrain", "Comoros", "Djibouti", "Egypt", "Iraq", "Jordan", "Kuwait", "Lebanon", "Libya", "Mauritania", "Morocco", "Oman", "Palestine", "Qatar", "Saudi Arabia", "Somalia", "Sudan", "Syria*", "Tunisia", "the United Arab Emirates", "Yemen" }));
        country_Cb.setSelectedIndex(4);
        country_Cb.setToolTipText("");
        country_Cb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 32, 44), 1, true));
        country_Cb.setFocusable(false);
        country_Cb.setLightWeightPopupEnabled(false);
        country_Cb.setVerifyInputWhenFocusTarget(false);
        main_panel.add(country_Cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 212, 242, 31));

        jLabel19.setFont(new java.awt.Font("Rubik", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(136, 140, 173));
        jLabel19.setText("Phone");
        main_panel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 56, -1));

        jLabel20.setFont(new java.awt.Font("Rubik", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(136, 140, 173));
        jLabel20.setText("Email");
        main_panel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 56, -1));

        email_tf.setEditable(false);
        email_tf.setBackground(new java.awt.Color(19, 20, 28));
        email_tf.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        email_tf.setForeground(new java.awt.Color(204, 204, 204));
        email_tf.setText("  Abdallah@gmail.com ");
        email_tf.setBorder(null);
        email_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_tfActionPerformed(evt);
            }
        });
        email_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                email_tfKeyPressed(evt);
            }
        });
        main_panel.add(email_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 210, 31));

        new_password_tf.setBackground(new java.awt.Color(19, 20, 28));
        new_password_tf.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        new_password_tf.setForeground(new java.awt.Color(204, 204, 204));
        new_password_tf.setAlignmentX(2.0F);
        new_password_tf.setBorder(null);
        new_password_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_password_tfActionPerformed(evt);
            }
        });
        main_panel.add(new_password_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 182, 31));

        jLabel25.setFont(new java.awt.Font("Rubik", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(136, 140, 173));
        jLabel25.setText("New password");
        main_panel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        jLabel26.setFont(new java.awt.Font("Rubik", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(136, 140, 173));
        jLabel26.setText("Retype new password");
        main_panel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        jLabel27.setFont(new java.awt.Font("Rubik", 1, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(136, 140, 173));
        jLabel27.setText("Old password");
        main_panel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        phone_tf.setEditable(false);
        phone_tf.setBackground(new java.awt.Color(19, 20, 28));
        phone_tf.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        phone_tf.setForeground(new java.awt.Color(204, 204, 204));
        phone_tf.setText(" 01277535307");
        phone_tf.setBorder(null);
        phone_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_tfActionPerformed(evt);
            }
        });
        phone_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phone_tfKeyPressed(evt);
            }
        });
        main_panel.add(phone_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 100, 31));

        name_tf.setEditable(false);
        name_tf.setBackground(new java.awt.Color(19, 20, 28));
        name_tf.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        name_tf.setForeground(new java.awt.Color(204, 204, 204));
        name_tf.setText("  Abdallah Mohamed");
        name_tf.setBorder(null);
        name_tf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        name_tf.setPreferredSize(new java.awt.Dimension(250, 30));
        name_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_tfActionPerformed(evt);
            }
        });
        main_panel.add(name_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, 20));
        main_panel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 100, 10));

        age_tf.setEditable(false);
        age_tf.setBackground(new java.awt.Color(19, 20, 28));
        age_tf.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        age_tf.setForeground(new java.awt.Color(204, 204, 204));
        age_tf.setText("21");
        age_tf.setBorder(null);
        age_tf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        age_tf.setPreferredSize(new java.awt.Dimension(250, 30));
        age_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_tfActionPerformed(evt);
            }
        });
        main_panel.add(age_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 30, -1));
        main_panel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 170, 20));
        main_panel.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 40, 20));
        main_panel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 210, 20));
        main_panel.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 180, 20));
        main_panel.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 180, 20));

        old_password_tf.setBackground(new java.awt.Color(19, 20, 28));
        old_password_tf.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        old_password_tf.setForeground(new java.awt.Color(204, 204, 204));
        old_password_tf.setAlignmentX(2.0F);
        old_password_tf.setBorder(null);
        old_password_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                old_password_tfActionPerformed(evt);
            }
        });
        main_panel.add(old_password_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 182, 31));
        main_panel.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 180, 10));

        new_password2_tf.setBackground(new java.awt.Color(19, 20, 28));
        new_password2_tf.setFont(new java.awt.Font("Rubik", 0, 12)); // NOI18N
        new_password2_tf.setForeground(new java.awt.Color(204, 204, 204));
        new_password2_tf.setAlignmentX(2.0F);
        new_password2_tf.setBorder(null);
        new_password2_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_password2_tfActionPerformed(evt);
            }
        });
        main_panel.add(new_password2_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 182, 31));

        jLabel30.setBackground(new java.awt.Color(0, 153, 255));
        jLabel30.setFont(new java.awt.Font("Rubik", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 153, 255));
        jLabel30.setText("Plan Details");
        main_panel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 120, 34));

        myButton2.setBackground(new java.awt.Color(0, 153, 255));
        myButton2.setBorder(null);
        myButton2.setForeground(new java.awt.Color(204, 204, 204));
        myButton2.setText("Update");
        myButton2.setColor(new java.awt.Color(0, 153, 255));
        myButton2.setColorClick(new java.awt.Color(0, 153, 255));
        myButton2.setColorOver(new java.awt.Color(30, 32, 44));
        myButton2.setFocusable(false);
        myButton2.setFont(new java.awt.Font("Rubik", 1, 16)); // NOI18N
        myButton2.setRadius(50);
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });
        main_panel.add(myButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 110, 50));

        roundedPanel1.setBackground(new java.awt.Color(30, 32, 44));
        roundedPanel1.setFont(new java.awt.Font("Rubik", 1, 12)); // NOI18N
        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myButton1.setBackground(new java.awt.Color(0, 153, 255));
        myButton1.setBorder(null);
        myButton1.setForeground(new java.awt.Color(204, 204, 204));
        myButton1.setText("Change Plan");
        myButton1.setBorderColor(new java.awt.Color(0, 153, 255));
        myButton1.setColor(new java.awt.Color(0, 153, 255));
        myButton1.setColorClick(new java.awt.Color(0, 153, 255));
        myButton1.setColorOver(new java.awt.Color(30, 32, 44));
        myButton1.setFocusable(false);
        myButton1.setFont(new java.awt.Font("Rubik", 1, 16)); // NOI18N
        myButton1.setRadius(50);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        roundedPanel1.add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 312, 120, 50));

        platinum_btn.setBackground(new java.awt.Color(30, 32, 44));
        plan_Group.add(platinum_btn);
        platinum_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        platinum_btn.setForeground(new java.awt.Color(204, 204, 204));
        platinum_btn.setText("Platinum Plan");
        platinum_btn.setFocusable(false);
        platinum_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        platinum_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platinum_btnActionPerformed(evt);
            }
        });
        roundedPanel1.add(platinum_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 147, 312, 45));

        gold_btn.setBackground(new java.awt.Color(30, 32, 44));
        plan_Group.add(gold_btn);
        gold_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        gold_btn.setForeground(new java.awt.Color(204, 204, 204));
        gold_btn.setSelected(true);
        gold_btn.setText("Gold Plan");
        gold_btn.setFocusable(false);
        gold_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gold_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gold_btnActionPerformed(evt);
            }
        });
        roundedPanel1.add(gold_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 280, 45));

        Diamond_btn.setBackground(new java.awt.Color(30, 32, 44));
        plan_Group.add(Diamond_btn);
        Diamond_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Diamond_btn.setForeground(new java.awt.Color(204, 204, 204));
        Diamond_btn.setText("Diamond Plan");
        Diamond_btn.setFocusable(false);
        Diamond_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Diamond_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Diamond_btnActionPerformed(evt);
            }
        });
        roundedPanel1.add(Diamond_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 235, 312, 45));

        main_panel.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 340, 390));

        jLabel31.setBackground(new java.awt.Color(0, 153, 255));
        jLabel31.setFont(new java.awt.Font("Rubik", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 153, 255));
        jLabel31.setText("Account Details");
        main_panel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 160, 34));

        jPanel1.setBackground(new java.awt.Color(19, 20, 28));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Rubik", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(136, 140, 173));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Profile");

        big_name.setBackground(new java.awt.Color(204, 204, 204));
        big_name.setFont(new java.awt.Font("Rubik", 1, 48)); // NOI18N
        big_name.setForeground(new java.awt.Color(204, 204, 204));
        big_name.setText("Abdallah Mohamed");

        big_plan.setFont(new java.awt.Font("Rubik", 1, 20)); // NOI18N
        big_plan.setForeground(new java.awt.Color(0, 153, 255));
        big_plan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        big_plan.setText("GOLD PLAN");

        imagePanel2.setPreferredSize(new java.awt.Dimension(200, 200));

        imagePanel2.setImage("C:\\EgyEast_Image\\icons\\profile1.png");

        javax.swing.GroupLayout imagePanel2Layout = new javax.swing.GroupLayout(imagePanel2);
        imagePanel2.setLayout(imagePanel2Layout);
        imagePanel2Layout.setHorizontalGroup(
            imagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        imagePanel2Layout.setVerticalGroup(
            imagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(imagePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(big_name, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(big_plan, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1370, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(big_name, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(big_plan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(imagePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        main_panel.getAccessibleContext().setAccessibleParent(main_panel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void email_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_tfActionPerformed

    private void email_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_email_tfKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_tfKeyPressed

    private void new_password_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_password_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_password_tfActionPerformed

    private void name_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_tfActionPerformed

    private void age_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_tfActionPerformed

    private void phone_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone_tfKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_tfKeyPressed

    private void phone_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_tfActionPerformed

    private void old_password_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_old_password_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_old_password_tfActionPerformed

    private void new_password2_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_password2_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_password2_tfActionPerformed

    private void Diamond_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Diamond_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Diamond_btnActionPerformed

    private void gold_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gold_btnActionPerformed

    }//GEN-LAST:event_gold_btnActionPerformed

    private void platinum_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platinum_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_platinum_btnActionPerformed

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
   
    }//GEN-LAST:event_myButton1ActionPerformed

    private void homebtnlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnlMouseEntered

        setHover(homebtnl,light_bg,text_hover);

    }//GEN-LAST:event_homebtnlMouseEntered

    private void homebtnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnlMouseExited
        resetHover(homebtnl,light_bg,white_text);
    }//GEN-LAST:event_homebtnlMouseExited

    private void homebtnlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnlMousePressed
         home.setVisible(true);
         user_account.setVisible(false);
       
    }//GEN-LAST:event_homebtnlMousePressed

    private void homeImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeImageMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_homeImageMouseEntered

    private void homeImageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeImageMousePressed
       home.setVisible(true);
       user_account.setVisible(false);
        
    }//GEN-LAST:event_homeImageMousePressed

    private void homebtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMousePressed
        home.setVisible(true);
        user_account.setVisible(false);
       
    }//GEN-LAST:event_homebtnMousePressed

    private void logoutbtnlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnlMouseEntered
        setHover(logoutbtnl,light_bg,new Color(251,99,99));
    }//GEN-LAST:event_logoutbtnlMouseEntered

    private void logoutbtnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnlMouseExited
        resetHover(logoutbtnl,light_bg,white_text);
    }//GEN-LAST:event_logoutbtnlMouseExited

    private void logoutbtnlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnlMousePressed
                System.exit(0);
    }//GEN-LAST:event_logoutbtnlMousePressed

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        // TODO add your handling code here:
                System.exit(0);
    }//GEN-LAST:event_logoutMousePressed

    private void logoutbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMousePressed
                System.exit(0);
    }//GEN-LAST:event_logoutbtnMousePressed

    private void favourtiebtnlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favourtiebtnlMouseEntered
        setHover(favourtiebtnl,light_bg,text_hover);
    }//GEN-LAST:event_favourtiebtnlMouseEntered

    private void favourtiebtnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favourtiebtnlMouseExited
        resetHover(favourtiebtnl,light_bg,white_text);
    }//GEN-LAST:event_favourtiebtnlMouseExited

    private void favourtiebtnlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favourtiebtnlMousePressed
                filmCardsFav.clear();
                favFrame.setVisible(true);
                user_account.setVisible(false);
    }//GEN-LAST:event_favourtiebtnlMousePressed

    private void favouritesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favouritesMousePressed
                filmCardsFav.clear();
                favFrame.setVisible(true);
                user_account.setVisible(false);
    }//GEN-LAST:event_favouritesMousePressed

    private void favouritesbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favouritesbtnMousePressed
                filmCardsFav.clear();
                favFrame.setVisible(true);
                user_account.setVisible(false);
    }//GEN-LAST:event_favouritesbtnMousePressed

    private void profilebtnlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilebtnlMouseEntered
        setHover(profilebtnl,light_bg,text_hover);
    }//GEN-LAST:event_profilebtnlMouseEntered

    private void profilebtnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilebtnlMouseExited
        resetHover(profilebtnl,light_bg,white_text);
    }//GEN-LAST:event_profilebtnlMouseExited

    private void profilebtnlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilebtnlMousePressed
    }//GEN-LAST:event_profilebtnlMousePressed

    private void profileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMousePressed
    }//GEN-LAST:event_profileMousePressed

    private void profilebtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilebtnMousePressed

    }//GEN-LAST:event_profilebtnMousePressed

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        try {
            // TODO add your handling code here:
            String old_password = String.valueOf(old_password_tf.getPassword());
            String real_old_password = CurrentUser.user_data.getString("password");
            if (old_password.equals(real_old_password)){
                String new_password = String.valueOf(new_password_tf.getPassword());
                String conf_new_password = String.valueOf(new_password2_tf.getPassword());
                if (new_password.equals(conf_new_password)){
                String sql = "UPDATE Users SET password = '" + new_password + "' WHERE User_id = " + CurrentUser.user_data.getString("User_id");
                updateData(sql);
                JOptionPane.showMessageDialog(User_account.this, "تم التغير يحبيب اخوك ");
                }
                else {
                    JOptionPane.showMessageDialog(User_account.this, "أتاكد من الباسوردين دول وتعالي");
                }
            }
            else {
                JOptionPane.showMessageDialog(User_account.this, "راجع معلوماتك القديمه ");
            }
        }
            catch (SQLException ex) {
            Logger.getLogger(User_account.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_myButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new User_account().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Diamond_btn;
    private javax.swing.JTextField age_tf;
    private javax.swing.JLabel big_name;
    private javax.swing.JLabel big_plan;
    private javax.swing.JComboBox<String> country_Cb;
    private javax.swing.JTextField email_tf;
    private ImagePrint.ImagePanel favourites;
    private EgyEast.com.roundedpanal.RoundedPanel favouritesbtn;
    private javax.swing.JLabel favourtiebtnl;
    private javax.swing.JComboBox<String> gender_Cb;
    private javax.swing.JRadioButton gold_btn;
    private ImagePrint.ImagePanel homeImage;
    private EgyEast.com.roundedpanal.RoundedPanel homebtn;
    private javax.swing.JLabel homebtnl;
    private ImagePanel.ImagePanel imagePanel2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel lbar;
    private ImagePrint.ImagePanel logout;
    private EgyEast.com.roundedpanal.RoundedPanel logoutbtn;
    private javax.swing.JLabel logoutbtnl;
    private javax.swing.JPanel main_panel;
    private newpackage.myButton myButton1;
    private newpackage.myButton myButton2;
    private javax.swing.JTextField name_tf;
    private javax.swing.JPasswordField new_password2_tf;
    private javax.swing.JPasswordField new_password_tf;
    private javax.swing.JPasswordField old_password_tf;
    private javax.swing.JTextField phone_tf;
    private javax.swing.ButtonGroup plan_Group;
    private javax.swing.JRadioButton platinum_btn;
    private ImagePrint.ImagePanel profile;
    private EgyEast.com.roundedpanal.RoundedPanel profilebtn;
    private javax.swing.JLabel profilebtnl;
    private newpackage.RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables

    
}
