/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.egyeastlogin;

import EgyEast.Home;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.*;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import java.util.UUID;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import Custom_Components.ImagePanel;
import ChoosePlan.*;
import static com.mycompany.egyeastlogin.EgyEastLogin.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Robaa
 */
public class SignUp extends javax.swing.JFrame {
    /**
     * Creates new form SignUp
     */
    public SignUp() {
        ImageIcon img = new ImageIcon("C:\\EgyEast_Image\\icons/EgyEast.png");
          this.setIconImage(img.getImage());
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        imagePanel1 = new Custom_Components.ImagePanel();
        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        name_tf = new javax.swing.JTextField();
        age_tf = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        female_btn = new javax.swing.JRadioButton();
        male_btn = new javax.swing.JRadioButton();
        passwordLabel = new javax.swing.JLabel();
        confirmPassLabel = new javax.swing.JLabel();
        SignUpBtn = new com.mycompany.egyeastlogin.myButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        password_tf = new javax.swing.JPasswordField();
        password_con_tf = new javax.swing.JPasswordField();
        confirmPassLabel1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        confirmPassLabel2 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        confirmPassLabel3 = new javax.swing.JLabel();
        country_cb = new javax.swing.JComboBox<>();
        email_tf = new javax.swing.JTextField();
        phone_tf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EgyEast");
        setBackground(new java.awt.Color(255, 255, 255));
        setFocusable(false);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(19, 20, 28));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(30, 32, 44));
        jPanel3.setPreferredSize(new java.awt.Dimension(600, 800));

        imagePanel1.setBackground(new java.awt.Color(255, 255, 255));
        imagePanel1.setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        setImage(imagePanel1 , "C:\\EgyEast_Image\\icons\\login-Pic.png");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(imagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(imagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Rubik Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create Your Account");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 290, -1));

        nameLabel.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Name");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 60, -1));

        name_tf.setBackground(new java.awt.Color(19, 20, 28));
        name_tf.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        name_tf.setForeground(new java.awt.Color(255, 255, 255));
        name_tf.setBorder(null);
        jPanel1.add(name_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 250, 30));

        age_tf.setBackground(new java.awt.Color(19, 20, 28));
        age_tf.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        age_tf.setForeground(new java.awt.Color(255, 255, 255));
        age_tf.setBorder(null);
        jPanel1.add(age_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 250, 30));

        emailLabel.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Email");
        jPanel1.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 45, -1));

        jLabel4.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gender");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, 65, -1));

        female_btn.setBackground(new java.awt.Color(19, 20, 28));
        gender.add(female_btn);
        female_btn.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        female_btn.setForeground(new java.awt.Color(255, 255, 255));
        female_btn.setText("Female");
        female_btn.setToolTipText("");
        female_btn.setFocusPainted(false);
        female_btn.setFocusable(false);
        female_btn.setName("gender"); // NOI18N
        female_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_btnActionPerformed(evt);
            }
        });
        jPanel1.add(female_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 630, -1, -1));

        male_btn.setBackground(new java.awt.Color(19, 20, 28));
        gender.add(male_btn);
        male_btn.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        male_btn.setForeground(new java.awt.Color(255, 255, 255));
        male_btn.setText("Male");
        male_btn.setFocusPainted(false);
        male_btn.setFocusable(false);
        male_btn.setName("gender"); // NOI18N
        male_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                male_btnActionPerformed(evt);
            }
        });
        jPanel1.add(male_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 630, -1, -1));

        passwordLabel.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password");
        jPanel1.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 90, -1));

        confirmPassLabel.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        confirmPassLabel.setForeground(new java.awt.Color(255, 255, 255));
        confirmPassLabel.setText("Confirm Pass");
        jPanel1.add(confirmPassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, 27));

        SignUpBtn.setBackground(new java.awt.Color(11, 149, 255));
        SignUpBtn.setBorder(null);
        SignUpBtn.setForeground(new java.awt.Color(255, 255, 255));
        SignUpBtn.setText("SignUp");
        SignUpBtn.setBorderColor(new java.awt.Color(11, 149, 255));
        SignUpBtn.setColor(new java.awt.Color(11, 149, 255));
        SignUpBtn.setColorClick(new java.awt.Color(19, 20, 28));
        SignUpBtn.setFocusable(false);
        SignUpBtn.setFont(new java.awt.Font("Rubik Black", 0, 14)); // NOI18N
        SignUpBtn.setRadius(15);
        SignUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SignUpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 680, 260, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 250, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 250, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 250, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 250, 10));

        password_tf.setBackground(new java.awt.Color(19, 20, 28));
        password_tf.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        password_tf.setForeground(new java.awt.Color(255, 255, 255));
        password_tf.setBorder(null);
        jPanel1.add(password_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 250, 30));

        password_con_tf.setBackground(new java.awt.Color(19, 20, 28));
        password_con_tf.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        password_con_tf.setForeground(new java.awt.Color(255, 255, 255));
        password_con_tf.setToolTipText("");
        password_con_tf.setBorder(null);
        password_con_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_con_tfActionPerformed(evt);
            }
        });
        jPanel1.add(password_con_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 250, 30));

        confirmPassLabel1.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        confirmPassLabel1.setForeground(new java.awt.Color(255, 255, 255));
        confirmPassLabel1.setText("Phone");
        jPanel1.add(confirmPassLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, 27));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 250, 10));

        confirmPassLabel2.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        confirmPassLabel2.setForeground(new java.awt.Color(255, 255, 255));
        confirmPassLabel2.setText("Age");
        jPanel1.add(confirmPassLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 40, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 250, 10));

        confirmPassLabel3.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        confirmPassLabel3.setForeground(new java.awt.Color(255, 255, 255));
        confirmPassLabel3.setText("Country");
        jPanel1.add(confirmPassLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 80, 30));

        country_cb.setBackground(new java.awt.Color(19, 20, 28));
        country_cb.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        country_cb.setForeground(new java.awt.Color(255, 255, 255));
        country_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Algeria", "Bahrain", "Comoros", "Djibouti", "Egypt", "Iraq", "Jordan", "Kuwait", "Lebanon", "Libya", "Mauritania", "Morocco", "Oman", "Palestine", "Qatar", "Saudi Arabia", "Somalia", "Sudan", "Syria", "Tunisia", "the United Arab Emirates", "Yemen" }));
        country_cb.setSelectedIndex(4);
        country_cb.setBorder(null);
        country_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                country_cbActionPerformed(evt);
            }
        });
        jPanel1.add(country_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, 250, 40));

        email_tf.setBackground(new java.awt.Color(19, 20, 28));
        email_tf.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        email_tf.setForeground(new java.awt.Color(255, 255, 255));
        email_tf.setBorder(null);
        jPanel1.add(email_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 250, 30));

        phone_tf.setBackground(new java.awt.Color(19, 20, 28));
        phone_tf.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        phone_tf.setForeground(new java.awt.Color(255, 255, 255));
        phone_tf.setBorder(null);
        jPanel1.add(phone_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 250, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1214, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public static String user_data;
    private void SignUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpBtnActionPerformed
        // TODO add your handling code here:
         
         String name = name_tf.getText();
         String email = email_tf.getText();
         String password = String.valueOf(password_tf.getPassword());
         String phone = phone_tf.getText();
         int age = Integer.parseInt(age_tf.getText());
         String country = country_cb.getSelectedItem().toString();
         String gender = "";
         boolean flag = true;
         // Male or Female
         if (male_btn.isSelected()){
             gender = "Male";
         }
         else if (female_btn.isSelected()) {
             gender = "Female";
         }
         else {
                    JOptionPane.showMessageDialog(SignUp.this, "أنت راجل ولا ست يعم ");
                    flag = false;
         }
         // Password Check
         if (!(password.equals(String.valueOf(password_con_tf.getPassword()) ))){
             JOptionPane.showMessageDialog(SignUp.this, "أكتب الباسورد صح يرجوله");
             flag = false;
         }
         
         // SQL Conn
         if (flag){
             try{
         String sql = "insert into [Users] (name, email, age, country, phone, gender , password) values(?, ?, ?, ?, ?, ?, ?)";
         PreparedStatement ps = EgyEastLogin.conn.prepareStatement(sql);
         ps.setString(1, name);
         ps.setString(2,email);
         ps.setInt(3,age);
         ps.setString(4, country);
         ps.setString(5, phone);
         ps.setString(6, gender);
         ps.setString(7, password);
         ps.executeUpdate();
         user_data(email);
         JOptionPane.showMessageDialog(SignUp.this, "ضن يرجوله ");
         chooseplan = new Chooseplan();
         chooseplan.setVisible(true);
         dispose();
         }
          catch(Exception ex){
                ex.printStackTrace();
           }
         }
    }//GEN-LAST:event_SignUpBtnActionPerformed
    public static void user_data(String email){
       String Query = "SELECT * FROM Users WHERE Email = '" + email + "'";
       ResultSet x = retriveData(Query);
       try {
            x.next();
        } catch (SQLException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
       CurrentUser.user_data = x;
        
    }
    
    private void male_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_male_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_male_btnActionPerformed

    private void female_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_female_btnActionPerformed

    private void country_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_country_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_country_cbActionPerformed

    private void password_con_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_con_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_con_tfActionPerformed
    
    public void setImage(ImagePanel panel,String path){
     try{
            panel.setImage(ImageIO.read(new File(path)));
            }
            catch (IOException e) {
                    e.printStackTrace();
                       }
     }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SignUp().setVisible(true);            
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.egyeastlogin.myButton SignUpBtn;
    private javax.swing.JTextField age_tf;
    private javax.swing.JLabel confirmPassLabel;
    private javax.swing.JLabel confirmPassLabel1;
    private javax.swing.JLabel confirmPassLabel2;
    private javax.swing.JLabel confirmPassLabel3;
    private javax.swing.JComboBox<String> country_cb;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField email_tf;
    private javax.swing.JRadioButton female_btn;
    private javax.swing.ButtonGroup gender;
    private Custom_Components.ImagePanel imagePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JRadioButton male_btn;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField name_tf;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField password_con_tf;
    private javax.swing.JPasswordField password_tf;
    private javax.swing.JTextField phone_tf;
    // End of variables declaration//GEN-END:variables

}
